### ISSUE TITLE
Implement middleware capabilities

### ISSUE THREAD

**Issue by evilwalrus** [evilwalrus/Blubber#17]
Implement this, namely for caching.  Allow the API creator to implement their own caching mechanisms and pass them into Blubber to issue valid responses and validate conditional requests.

Another option is just to do built-in caching, but the caveat with this is that there are so many options out there, and to write drivers for all options would be unfeasible.  No need to reinvent the wheel here, but people don't always want file-based caching, but instead prefer to use Redis, Memcache(d), etc.

Make this a priority and get feedback about possible options/paths.

**Comment by evilwalrus** [comment]
@BigE Any thoughts on this? :thought_balloon:

**Comment by BigE** [comment]
First off, let me say from my Django experiences, middleware is **dangerous**. It can lead to code in your project that is very, very hard to trace and find. With that in mind... I still prefer the idea of allowing people to implement their own caching mechanisms rather than being forced to use a single implementation. If done right, the middleware option can be a very helpful feature in the ability to implement many more things than caching.

The alternative is to put the logic in a base view class that can handle all of these things in a centralized place that you can easily extend off of. I prefer this approach because it does keep the code in a single place in the project, but still allows you to override the request and response to do the things you need to do and have a proper code trail to trace when issues come up.

**Comment by evilwalrus** [comment]
Very good answer.  I think an adapter interface is a much better way to go:

``` php
class MemcachedCache implements \Blubber\Interface\CacheAdapterInterface
{
    ... your logic here ...
}
```

... where CacheAdapterInterface would outline a few essential methods that Blubber requires for use, and then you can just set it up as:

``` php
$app = new \Blubber\App(...);
$app->setCache(new MemcachedCache);
```

**Comment by evilwalrus** [comment]
closing this
